---
name: Push to Luarocks

on:
  push:
    branches: [main]
  release:
    types: [created]
    tags: ["*"]
  pull_request: # Tests installing the generated rockspec on PR without uploading
  workflow_dispatch:

env:
  LUAROCKS_SPECREV: 1

jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get scm Version
        if: github.event_name == 'push'
        run: echo "LUAROCKS_VERSION=scm" >> $GITHUB_ENV
      - name: Get tag Version
        if: github.event_name != 'push'
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - name: Get Revision
        if: github.event_name == 'push'
        run: echo "LUAROCKS_SPECREV=$(git log --oneline | wc -l)" >> $GITHUB_ENV

      # Needed to install the tree-sitter parser dependency
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install tree-sitter CLI
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tree-sitter-cli

      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          specrev: ${{ env.LUAROCKS_SPECREV }}
          dependencies: |
            neotest
            tree-sitter-c_sharp
            tree-sitter-fsharp
          copy_directories: |
            scripts
          labels: |
            "neovim"
            "neotest"
          summary: "Neotest adapter for dotnet"
